### ISSUE TITLE
Asap3 version 3.11.10 cannot be installed on certain on MacOS

### ISSUE THREAD

**Issue by ClaudioZeni** [kcl-tscm/mff#4]
Asap3 version 3.11.10 is required for the MFF package, and some on some Mac machines the installation of ASAP3 3.11.10 fails.

When installed through conda, ASAP3 3.10.10 is installed, which causes issues in the configurationsand calculator modules.

**Comment by fekad** [comment]
You could try to update the asap3 via pip install inside the conda environment:
`conda activate mff-env`
and
`pip install asap3 --force`
